CollinSally.Web/Controllers/CelebrationController.cs
using CollinSally.Web.Models;
using CollinSally.Web.ViewModels;
using Grady.Framework.Mvc;
using SendGrid;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.Entity;
using System.Linq;
using System.Net.Mail;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace CollinSally.Web.Controllers
{
    public class CelebrationController : Controller
    {
        [HttpGet]
        public ActionResult Rsvp()
        {
            return View();
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<ActionResult> Rsvp(RsvpViewModel model)
        {
            if (!string.IsNullOrWhiteSpace(model.Website) || model.CaptchaPass == null || model.CaptchaPass != "COLLINSALLY_NOT_ROBOT")
            {
                return Json(new { status = 0, error = "Only humans can submit this form." });
            }

            using (CollinSallyWedding db = new CollinSallyWedding())
            using (DbContextTransaction dbTrans = db.Database.BeginTransaction())
            {
                RSVP rsvp = new RSVP
                {
                    Attending = model.Attending,
                    EmailAddress = model.EmailAddress
                };

                db.RSVPs.Add(rsvp);

                try
                {
                    await db.SaveChangesAsync();
                }
                catch (Exception ex)
                {
                    dbTrans.Rollback();

                    return Json(new { status = 0, error = ex.Message });
                }

                RSVPAttendee primeAttendee = new RSVPAttendee
                {
                    EmailAddress = model.EmailAddress,
                    Name = model.Name,
                    RSVP_ID = rsvp.ID
                };

                db.RSVPAttendees.Add(primeAttendee);

                foreach (RSVPAttendee dbAttendee in model.Attendees.Where(attendee => attendee.EmailAddress != null).Select(attendee => new RSVPAttendee
                {
                    EmailAddress = attendee.EmailAddress,
                    Name = attendee.Name,
                    RSVP_ID = rsvp.ID
                }))
                {
                    db.RSVPAttendees.Add(dbAttendee);
                }

                try
                {
                    await db.SaveChangesAsync();
                    dbTrans.Commit();
                }
                catch (Exception ex)
                {
                    dbTrans.Rollback();

                    return Json(new { status = 0, error = ex.Message });
                }

                await SendRsvpEmailAsync(model);
            }

            return Json(new { status = 1 });
        }

        [HttpGet]
        public ActionResult Location()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Photos()
        {
            return View();
        }

        #region Manage RSVPs

        public ActionResult Manage()
        {
            bool? isAuthenticated = Session["IsAuthenticated"] as bool?;

            bool? badPass = TempData["BadPass"] as bool?;

            if (badPass.HasValue && badPass.Value) ViewBag.BadPass = true;

            return View(isAuthenticated.HasValue && isAuthenticated.Value ? "Manage" : "SecurityCheck");
        }

        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Manage(string password)
        {
            if (!string.IsNullOrWhiteSpace(password) && password == "Maggie2016")
            {
                Session["IsAuthenticated"] = true;
            }
            else
            {
                TempData["BadPass"] = true;
            }

            return Manage();
        }

        public async Task<JsonResult> Read(int? id)
        {
            using (CollinSallyWedding db = new CollinSallyWedding())
            {
                switch (id)
                {
                    case 1:
                        return Json(await db.RSVPs.CountAsync(), JsonRequestBehavior.AllowGet);

                    case 2:
                        return Json(await db.RSVPs.CountAsync(x => x.Attending), JsonRequestBehavior.AllowGet);

                    case 3:
                        return Json(await db.RSVPs.CountAsync(x => !x.Attending), JsonRequestBehavior.AllowGet);
                }

                List<RsvpExistingViewModel> existingRsvps = await (from ra in db.RSVPAttendees
                                                                   join r in db.RSVPs on ra.RSVP_ID equals r.ID
                                                                   select new RsvpExistingViewModel
                                                                   {
                                                                       ID = r.ID,
                                                                       Name = ra.Name,
                                                                       EmailAddress = ra.EmailAddress,
                                                                       Attending = r.Attending
                                                                   }).ToListAsync();

                return Json(new
                {
                    data = existingRsvps
                        .Distinct()
                        .Select(x => new
                        {
                            x.ID,
                            x.Name,
                            EmailAddress = "<a href='mailto:" + x.EmailAddress + "'>" + x.EmailAddress + "</a>",
                            Attending = x.Attending ? "Yes" : "No"
                        })
                }, JsonRequestBehavior.AllowGet);
            }
        }

        #endregion

        [HttpGet]
        public async Task<ActionResult> TestEmail()
        {
            await SendRsvpEmailAsync(new RsvpViewModel
            {
                Attendees = new List<RsvpAttendeeViewModel>
                {
                    new RsvpAttendeeViewModel
                    {
                        EmailAddress = "cgrady17@outlook.com",
                        Name = "Connor Grady"
                    }
                },
                Attending = true,
                EmailAddress = "cgrady17@outlook.com",
                Name = "Connor Grady",
                OtherAttendees = false
            });

            return HttpNotFound();
        }

        private async Task SendRsvpEmailAsync(RsvpViewModel model)
        {
            SendGridMessage message = new SendGridMessage
            {
                From = new MailAddress("sally-collin@collinsally.com", "Sally & Collin Grady"),
                Subject = "RSVP Confirmation | Sally & Collin's Celebration",
                Html = this.RenderPartialViewToString("RSVPEmail", model)
            };

            message.AddTo($"{model.Name} <{model.EmailAddress}>");

            SendGrid.Web transportWeb = new SendGrid.Web(ConfigurationManager.AppSettings["sendgrid:APIKey"]);

            await transportWeb.DeliverAsync(message);
        }
    }
}

CollinSally.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title | Collin &amp; Sally Grady</title>
    @Styles.Render("~/Content/CSS")
    @RenderSection("HeaderScripts", false)
    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date(); a = s.createElement(o),
            m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
        })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-8546022-17', 'auto');
        ga('send', 'pageview');
    </script>
</head>
<body>
    <header class="horizontal-w sm-rgt-mn @(ViewBag.IsHome == true ? "homepage" : "")">
        <div class="container">
            <div class="col-md-3 col-sm-3 logo-wrap">
                <div class="logo">
                    <a href="@Url.Action("Index", "Home")">
                        <img src="@Url.Content("~/Content/Images/logo.png")" width="275" id="img-logo-w1" alt="logo" class="img-logo-w1">
                    </a>
                </div>
                <div id="menu-icon">
                    <span class="glyphicon glyphicon-menu-hamburger"></span>
                </div>
            </div>
            <nav id="nav-wrap" class="nav-wrap1 col-md-9 col-sm-9">
                <div class="container">
                    <ul id="nav">
                        <li>@Html.ActionLink("RSVP", "RSVP", "Celebration")</li>
                        <li>@Html.ActionLink("Location", "Location", "Celebration")</li>
                        <li>@Html.ActionLink("Photos", "Photos", "Celebration")</li>
                    </ul>
                </div>
            </nav>
        </div>
    </header>

    <div>
        @RenderBody()
    </div>

    @if (ViewBag.IsHome != true)
    {
        <footer id="footer">
            <div class="row">
                <div class="col-lg-2">
                </div>
                <div class="col-lg-5">
                    <h2>
                        Sally <span class="glyphicon glyphicon-heart"></span> Collin
                    </h2>
                </div>
                <div class="col-lg-4">
                    <a href="@Url.Action("Index", "Home")" id="footer-logo"></a>
                    <p>Copyright &copy; 2016@(DateTime.Now.Year > 2016 ? " - " + DateTime.Now.Year : "") @Html.ActionLink("CollinSally.com", "Index", "Home"). All Rights Reserved.</p>
                    <p>Designed, Developed, and Hosted by Connor Grady.</p>
                    <p>CollinSally.com @($"v{ViewContext.Controller.GetType().Assembly.GetName().Version}")</p>
                </div>
            </div>
        </footer>
    }
    @Scripts.Render("~/Assets/Scripts")
    @RenderSection("FooterScripts", required: false)
</body>
</html>